[HTTP]
host="localhost"
port=80
[MYSQL]
database="config_center"
host="localhost"
port=3306
username="root"
password="1234"
[MONGODB]
database="config_center"
host="localhost"
port=27017
username="root"
password="1234"
